export const periodicElements = [
  {
    position: 1,
    name: 'Hydrogen',
    date: new Date('2020-04-05'),
    weight: 1.0079,
    symbol: 'H',
    translations: [
      { lang: 'French', translation: 'Hydrogène' },
      { lang: 'Spanish', translation: 'Hidrógeno' },
      { lang: 'German', translation: 'Wasserstoff' },
    ],
  },
  {
    position: 2,
    name: 'Helium',
    date: new Date('2020-05-04'),
    weight: 4.0026,
    symbol: 'He',
    translations: [
      { lang: 'French', translation: 'Hélium' },
      { lang: 'Spanish', translation: 'Helio' },
      { lang: 'German', translation: 'Helium' },
    ],
  },
  {
    position: 3,
    name: 'Lithium',
    date: new Date('2020-10-20'),
    weight: 6.941,
    symbol: 'Li',
    translations: [
      { lang: 'French', translation: 'Lithium' },
      { lang: 'Spanish', translation: 'Litio' },
      { lang: 'German', translation: 'Lithium' },
    ],
  },
  {
    position: 4,
    name: 'Beryllium',
    date: new Date('2020-02-09'),
    weight: 9.0122,
    symbol: 'Be',
    translations: [
      { lang: 'French', translation: 'Béryllium' },
      { lang: 'Spanish', translation: 'Berilio' },
      { lang: 'German', translation: 'Beryllium' },
    ],
  },
  {
    position: 5,
    name: 'Boron',
    date: new Date('2020-11-29'),
    weight: 10.811,
    symbol: 'B',
    translations: [
      { lang: 'French', translation: 'Bore' },
      { lang: 'Spanish', translation: 'Boro' },
      { lang: 'German', translation: 'Bor' },
    ],
  },
  {
    position: 6,
    name: 'Carbon',
    date: new Date('2020-08-01'),
    weight: 12.0107,
    symbol: 'C',
    translations: [
      { lang: 'French', translation: 'Carbone' },
      { lang: 'Spanish', translation: 'Carbón' },
      { lang: 'German', translation: 'Kohlenstoff' },
    ],
  },
  {
    position: 7,
    name: 'Nitrogen',
    date: new Date('2020-01-24'),
    weight: 14.0067,
    symbol: 'N',
    translations: [
      { lang: 'French', translation: 'Azote' },
      { lang: 'Spanish', translation: 'Nitrógeno' },
      { lang: 'German', translation: 'Stickstoff' },
    ],
  },
  {
    position: 8,
    name: 'Oxygen',
    date: new Date('2020-03-05'),
    weight: 15.9994,
    symbol: 'O',
    translations: [
      { lang: 'French', translation: 'Oxygène' },
      { lang: 'Spanish', translation: 'Oxígeno' },
      { lang: 'German', translation: 'Sauerstoff' },
    ],
  },
  {
    position: 9,
    name: 'Fluorine',
    date: new Date('2020-06-22'),
    weight: 18.9984,
    symbol: 'F',
    translations: [
      { lang: 'French', translation: 'Fluor' },
      { lang: 'Spanish', translation: 'Flúor' },
    ],
  },
  {
    position: 10,
    name: 'Neon',
    date: new Date('2020-05-05'),
    weight: 20.1797,
    symbol: 'Ne',
    translations: [
      { lang: 'French', translation: 'Néon' },
      { lang: 'Spanish', translation: 'Neón' },
    ],
  },
];
